name: Mealbook workflow

on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Build and Test mealbook project
    runs-on: macOS-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Testing iOS app
        run: |
        chmod +x ./.github/scripts/test_mealbook.sh
        exec ./.github/scripts/test_mealbook.sh
