name: Mealbook workflow

on: [push, pull_request]

jobs:
  test:
    name: Build and Test mealbook project
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Testing iOS app
        run: |
          chmod +x ./.github/scripts/test_mealbook.sh
          exec ./.github/scripts/test_mealbook.sh
