name: Mealbook workflow

on: [push, pull_request]

jobs:
  test:
    name: Build and Test mealbook project
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Unit tests
        run: bundle exec fastlane tests
